[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Double Glazing (description)
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "elseif _c.effect == 'Glass Card' then loc_vars = {cfg.Xmult, G.GAME.probabilities.normal, cfg.extra}"
position = 'at'
match_indent = true
payload = '''
elseif _c.effect == 'Glass Card' then loc_vars = {cfg.Xmult, G.GAME.probabilities.normal, double_glaze_glass_odds(cfg.extra)}
'''

# Extra pack options for Album Cover
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "SMODS.OPENED_BOOSTER = self"
position = "after"
match_indent = true
payload = '''
    SMODS.OPENED_BOOSTER.ability.extra = SMODS.OPENED_BOOSTER.ability.extra + (G.GAME.extra_pack_cards or 0)
'''

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "function add_round_eval_row(config)"
position = "after"
match_indent = true
payload = '''
    if config and config.name == 'interest' then G.GAME.interest_this_round = config.dollars end
'''
